---
format: html
---

# Resistência de genótipos de *Coffea canephora* ao parasitismo por *Meloidogyne paranaensis*

Os fitonematoides do gênero *Meloidogyne*, são uns dos principais causadores de danos a cultura do café, atrasando o desenvolvimento, reduzindo a produção e, dependendo da espécie, provocando a morte de plantas. Quando *M. incognita* e/ou *M. paranaensis* estão presentes numa lavoura, é comum que ocorra a morte de plantas adultas, devido aos sintomas de descortiçamento que causam às raízes, afetando a absorção de água e nutrientes pela planta, reduzindo o crescimento, induzindo sintomas de deficiência nutricional e provocando redução significativa da produtividade. O objetivo da pesquisa foi avaliar o comportamento genético dos genótipos de robusta e conilon quanto ao parasitismo por *M. paranaensis*. O experimento foi conduzido em condições de viveiro no Instituto Federal de Educação, Ciência e Tecnologia do Espírito Santo -- campus Santa Teresa, de março a outubro de 2021. Utilizou-se o delineamento experimental em blocos casualizados com 26 tratamentos e quatro repetições. Cada unidade experimental foi composta por três mudas. Os clones avaliados foram: VR8, R25, VR11, LB33, LB15, 180, AS2, R22, CM1, 06, G20, LB80, VR1, PDP, G4, 2.9, G2, RMD, 07, JC221, 110, VR4, VR3, R08 e 101. Como padrão de resistência foi usada a variedade Catucaí 785/15. O inóculo de *M. paranaensis* foi coletado em lavoura de café conilon naturalmente infestada pelo patógeno no município de Sooretama. As mudas de cada genótipo, contendo de quatro a cinco pares de folhas, foram inoculados com uma suspensão contendo 2000 ovos + J2 de *Meloidogyne paranaensis* (população inicial -- PI). O experimento foi mantido em viveiro após a inoculação por um período de 120 dias, quando as mudas foram cuidadosamente retiradas das sacolas plásticas e o sistema radicular separado do substrato e lavado com água. Avaliou-se o número de galhas formadas nas raízes de cada muda, atribuindo-se notas de 0 a 5, conforme escala proposta por Taylor e Sasser (1978). Avaliou-se também o número de ovos e J2 extraídos das raízes dos respectivos genótipos. A extração seguiu a metodologia de Coolen e Herde (1972). O nível de resistência de cada clone foi classificado de acordo com os critérios estabelecidos por Moura e Regis (1987).
